spring:
  thymeleaf:
    prefix: classpath:/templates/
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://45.129.8.170:3306/web_demo?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: ns2kracy
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

